apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-dapr-sample-client
  labels:
    app: oxygen-dapr-sample-client
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: oxygen-dapr-sample-client
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: oxygen-dapr-sample-client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "callservice"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: web
          image: oxygen-dapr-sample-client:debug
          imagePullPolicy: Never
          env:
          - name: Logging__Console__FormatterName
            value: "" 
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /run/desktop/mnt/host/e/dotnet_project/Oxygen-Dapr/sample/Client/bin/Debug/net7.0
        - name: v2
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Administrator/vsdbg/vs2017u5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-dapr-sample-server
  labels:
    app: oxygen-dapr-sample-server
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: oxygen-dapr-sample-server
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: oxygen-dapr-sample-server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "testservice"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: web
          image: oxygen-dapr-sample-server:debug
          imagePullPolicy: Never
          env:
          - name: Logging__Console__FormatterName
            value: "" 
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /run/desktop/mnt/host/e/dotnet_project/Oxygen-Dapr/sample/Server/bin/Debug/net7.0
        - name: v2
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Administrator/vsdbg/vs2017u5
---
apiVersion: v1
kind: Service 
metadata:
  name: oxygen-dapr-sample-server
spec:
  selector:
    app: oxygen-dapr-sample-server
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: oxygen-dapr-sample-client
spec:
  selector:
    app: oxygen-dapr-sample-client
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: oxygen-dapr
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.oxygen-dapr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oxygen-dapr-sample-client
            port:
              number: 80